### ISSUE TITLE
Netty swallows errors

### ISSUE THREAD

**Issue by AgentTroll** [TridentSDK/Trident#71]
Netty seems to have a thing with hiding errors thrown in packet handling classes such as NullPointerExceptions and the like. Unfortunately errors like these are difficult to trace and cause a lot of dumb behavior that should be spotted.

Not sure if this is an issue with `exceptionCaught` not being implemented in the initialized channel handlers?

**Comment by AgentTroll** [comment]
Could possibly be related to a few client issues...

```
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[21:01:57] [Client thread/INFO]: Setting user: Trolldude3
[21:02:01] [Client thread/WARN]: Skipping bad option: lastServer:
[21:02:01] [Client thread/INFO]: LWJGL Version: 2.9.4
[21:02:01] [Client thread/INFO]: Reloading ResourceManager: Default
[21:02:02] [Sound Library Loader/INFO]: Starting up SoundSystem...
[21:02:02] [Thread-5/INFO]: Initializing LWJGL OpenAL
[21:02:02] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:02:02] [Thread-5/INFO]: OpenAL initialized.
[21:02:03] [Sound Library Loader/INFO]: Sound engine started
[21:02:05] [Client thread/INFO]: Created: 1024x512 textures-atlas
[21:02:24] [Client thread/INFO]: Connecting to localhost, 25565
[21:02:26] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at h.a(SourceFile:47) [1.11.2.jar:?]
	at bes.av(SourceFile:962) [1.11.2.jar:?]
	at bes.a(SourceFile:398) [1.11.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.11.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at et.readBytes(SourceFile:759) ~[1.11.2.jar:?]
	at et.e(SourceFile:333) ~[1.11.2.jar:?]
	at bno.a(SourceFile:1523) ~[1.11.2.jar:?]
	at go.a(SourceFile:55) ~[1.11.2.jar:?]
	at go.a(SourceFile:9) ~[1.11.2.jar:?]
	at fo$1.run(SourceFile:13) ~[1.11.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at h.a(SourceFile:46) ~[1.11.2.jar:?]
	... 3 more
[21:02:26] [Client thread/INFO]: [CHAT] Trolldude3 joined the game
[21:04:02] [Client thread/INFO]: Connecting to localhost, 25565
[21:04:03] [Server Connector #2/ERROR]: Couldn't connect to server
java.io.IOException: Unable to connect to remote host: Connection refused
	at io.netty.channel.epoll.Native.finishConnect(Native Method) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doFinishConnect(EpollSocketChannel.java:659) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.finishConnect(EpollSocketChannel.java:592) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:621) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
[21:04:05] [Client thread/INFO]: Connecting to localhost, 25565
[21:04:06] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at h.a(SourceFile:47) [1.11.2.jar:?]
	at bes.av(SourceFile:962) [1.11.2.jar:?]
	at bes.a(SourceFile:398) [1.11.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.11.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at et.readBytes(SourceFile:759) ~[1.11.2.jar:?]
	at et.e(SourceFile:333) ~[1.11.2.jar:?]
	at bno.a(SourceFile:1523) ~[1.11.2.jar:?]
	at go.a(SourceFile:55) ~[1.11.2.jar:?]
	at go.a(SourceFile:9) ~[1.11.2.jar:?]
	at fo$1.run(SourceFile:13) ~[1.11.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at h.a(SourceFile:46) ~[1.11.2.jar:?]
	... 3 more
[21:04:06] [Client thread/INFO]: [CHAT] Trolldude3 joined the game
[21:04:35] [Client thread/INFO]: Connecting to localhost, 25565
[21:04:37] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at h.a(SourceFile:47) [1.11.2.jar:?]
	at bes.av(SourceFile:962) [1.11.2.jar:?]
	at bes.a(SourceFile:398) [1.11.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.11.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(116) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 1, widx: 10, cap: 10)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at et.readBytes(SourceFile:759) ~[1.11.2.jar:?]
	at et.e(SourceFile:333) ~[1.11.2.jar:?]
	at bno.a(SourceFile:1523) ~[1.11.2.jar:?]
	at go.a(SourceFile:55) ~[1.11.2.jar:?]
	at go.a(SourceFile:9) ~[1.11.2.jar:?]
	at fo$1.run(SourceFile:13) ~[1.11.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at h.a(SourceFile:46) ~[1.11.2.jar:?]
	... 3 more
[21:04:37] [Client thread/INFO]: [CHAT] Trolldude3 joined the game
```

**Comment by AgentTroll** [comment]
Actually no it probably isn't, I honestly have no idea what the error is....
