### ISSUE TITLE
Some packets throw IndexOutOfBounds

### ISSUE THREAD

**Issue by caojohnny** [TridentSDK/Trident#87]
```
Jul 01, 2017 9:03:17 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(222) + length(8) exceeds writerIndex(224): PooledUnsafeDirectByteBuf(ridx: 222, widx: 224, cap: 224)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(222) + length(8) exceeds writerIndex(224): PooledUnsafeDirectByteBuf(ridx: 222, widx: 224, cap: 224)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1389)
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:792)
	at io.netty.buffer.AbstractByteBuf.readDouble(AbstractByteBuf.java:818)
	at net.tridentsdk.server.packet.play.PlayInPosLook.read(PlayInPosLook.java:44)
	at net.tridentsdk.server.net.InDecoder.decode(InDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 14 more
```

**Comment by caojohnny** [comment]
I think it is because a handler is throwing an exception and preventing the packet from being read fully but again because netty seems to be swallowing all the exceptions, it isn't being printed until some retarded shit like this happens.

**Comment by caojohnny** [comment]
Apparently using `ReplayingDecoder` fixed this
